runtime: python37
instance_class: F1
default_expiration: "30s"

handlers:

# For a local Pyodide installation, activate below and run get-pyodide.py from project root.
#- url: /pyodide/(.*\.wasm)$
#  static_files: pyodide/\1
#  upload: pyodide/.*\.wasm$
#  mime_type: application/wasm
#- url: /pyodide
#  static_dir: pyodide

# Activate when vi_plugins should be enabled (order of the handlers matter!)
#- url: /vi/s/vi_plugins
#  static_dir: vi_plugins
- url: /vi/s
  static_dir: viur/vi
- url: /static
  static_dir: static
- url: /resources
  static_dir: viur/core/resources
- url: /favicon.ico
  static_files: static/meta/favicon.ico
  upload: favicon.ico
- url: /robots.txt
  static_files: static/meta/robots.txt
  upload: robots.txt

inbound_services:
- warmup

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "store_credentials.json"
