runtime: python37

# (1) Under some circumstances, you need to set a higher instance_class, like F2 or F4.
#     Unfortunatelly, this will increase App Engine cost, see https://cloud.google.com/appengine/pricing.
instance_class: F1
default_expiration: "30s"

# (2) To get more memory and concurrent requests, a separate gunicorn must be run.
entrypoint: gunicorn -b :$PORT -w 1 --threads 2 --disable-redirect-access-to-syslog main:app
automatic_scaling:
  max_concurrent_requests: 2

handlers:
# (3) For a local Pyodide installation, activate below and run get-pyodide.py from project root.
#     Leave the comments to use the CDN-version of Pyodide, which also runs very well.
#- url: /pyodide/(.*\.wasm)$
#  static_files: pyodide/\1
#  upload: pyodide/.*\.wasm$
#  mime_type: application/wasm
#- url: /pyodide
#  static_dir: pyodide

# (4) Activate this when vi_plugins should be used
#- url: /vi/s/vi_plugins
#  static_dir: vi_plugins

- url: /vi/s
  static_dir: viur/vi
- url: /static
  static_dir: static
- url: /resources
  static_dir: viur/core/resources
- url: /favicon.ico
  static_files: static/meta/favicon.ico
  upload: favicon.ico
- url: /robots.txt
  static_files: static/meta/robots.txt
  upload: robots.txt

inbound_services:
- warmup

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "store_credentials.json"
